### PR TITLE
Add support for helm repositories.

### LINKED ISSUE #283: helm repository configuration using playbook or in default/main.yaml file
Hi,

Can someone let me know if helm repository creation supports or not. if not then which version will support it, basically I want to configure helm repository using playbook same way as other repository, like yum, maven.

e.g
something like below we have for raw. do we have it for helm ?

nexus_config_raw: true
#Create raw hosted repository
    nexus_repos_raw_hosted:
      - name: CI-test-hosted-raw
        version_policy: release
        write_policy: allow_once  # one of "allow", "allow_once" or "deny"

### PR DESCRIPTION
**Pull request by delhage**
This PR adds support for configuring helm repositories
Fixes #283

### CODE REVIEW

**Comment by delhage** [comment]
If anyone like to try this, use `ansible-galaxy install -r requirements.yml`  with `requirements.yml`:
```
---
- name: ansible-ThoTeam.nexus3-oss
  src: https://github.com/delhage/nexus3-oss
  version: origin/add_helm_support
```

**Comment by delhage** [comment]
@zeitounator the continuous-integration/travis-ci check seems to be in waiting state forever. Seems a few more PR:s have the same problem

**Comment by zeitounator** [comment]
This  happened after switching from travis-ci.org to travis-ci.com. Didn't figure out how to fix the problem yet. Simply take into account the second report, which is ok in this case.

**Review by zeitounator — APPROVED** [review]

**Comment by zeitounator** [comment]
Sorry for the tremendous delay.

**Pull request merged**
