### PR TITLE
Add cleanup policies management

### LINKED ISSUE #218: Add cleanup policies management
Add the capabilities to add cleanup polices and apply it to a repository

### PR DESCRIPTION
**Pull request by cyrilbesse**
Fixes #218 (implementation)

### CODE REVIEW

**Comment by zeitounator** [comment]
Hi @cyrilbesse.

I pushed some commits to
* fix several namings
* add doc.
* fix defaults: cleanup policies should be empty and repos should not use any.
* push what you had done in defaults to molecule deployment for testing.
* merge latest changes from master so that later merge can succeed.

The CI build is on track. I'll check the result when I have time again. If the idempotence test still fails we'll see how to fix it.

Your latest update was a force push. Since I started to collaborate on that one, can you please avoid doing this for future contributions on this branch ? This will ensure we don't loose any work in the wild. Thanks in advance ! And thank you again for this contribution.

**Comment by cyrilbesse** [comment]
Hi @zeitounator 

I'm succeed to fix the idempotency problem

**Comment by djtjwillia** [comment]
@cyrilbesse @zeitounator Is it possible this may be merged soon? We are planning on using this and would love to have these features available :D

**Comment by zeitounator** [comment]
Hi @djtjwillia. I have plan to work on all pending request starting today for a release at the latest next week. Thanks for your interest.

**Pull request merged**
