### PR TITLE
In version 3.17 the default admin password is written to a file

### PR DESCRIPTION
**Pull request by radut**

### CODE REVIEW

**Comment by zeitounator** [comment]
Hi. Getting back as I can after quite some time totally off.

I don't really get what the changes in default example maven repositories and the groovy script to create them has to do with the changes for default admin password generation in 3.17. Is there something I missed ?

As you pointed out, this will definitely need a version detection mechanism to keep backward compatibility (as done with the url of the api endpoint, or the configuration files for example).

I'm going to work on this and release ASAP.

**Comment by radut** [comment]
As far as i remember I received validation error if blob store is missing.

**Comment by zeitounator** [comment]
Hi. Fix implemented in above PR. Thanks a lot for reporting and for giving clues. This was really helpful. I really appriciate.

I implemented things differently, avoiding to use shell and minimizing the number of changes on the groovy scripts to only what was failing with default playbook. As you can see, the blobtores/maven repos is not part of that. Let me know if you still have problems with that in your particular config.

If you look at the PR, you'll see I also implemented the version detection as well as the password file cleanup once password has been change to the new one.

Cheers.

**Comment by radut** [comment]
Hi
What about the: 
```
    if (!userDef.username.equals('anonymous')) {
        try {
            security.securitySystem.changePassword(userDef.username, userDef.password, userDef.password)
        } catch (InvalidCredentialsException ignored) {
            security.securitySystem.changePassword(userDef.username, userDef.password)
            currentResult.put('status', 'updated')
            scriptResults['changed'] = true
        }
    }
```

Did you tried to asign different roles to anonymous user ? like a custom anonymous role, where you have read only access to particular repos. :-?

**Comment by radut** [comment]
+ Is there any way to escape from the UI(modal) when you first login as admin. 
Where you configure the checkbox to enable / disble anonymous usage.

**Pull request closed without merging**
