### PR TITLE
Add apt support

### LINKED ISSUE #191: Integrate management of Apt repositories.
Nexus supports [apt repository natively since version 3.17.0](https://help.sonatype.com/repomanager3/release-notes/2019-release-notes#id-2019ReleaseNotes-RepositoryManager3.17.0)

Management of this repo format should be integrated to the role.

### PR DESCRIPTION
**Pull request by vitkhab**
Added support for apt hosted and proxy repos. Added test configuration into test cases.

Tested apt repos produced by the role manually.

Fixes #191

### CODE REVIEW

**Comment by vitkhab** [comment]
Public GPG key from test case
```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQGNBF2Ym3ABDACtu4R3enO2TehVslkRXc4ZcMkaAMIcJgOLo/IQBUnN8dInGLFR
upY2zF5zVND0eMxiGdv2D48wicHqPiiHMmeLS3IYuY5sXTeS9Tk0g6+ZvakkobGR
2k4GtxPAnbNxUB9gk232sRQObK1/QYRjNG8IYBsYKyMeSQiIl66kS/vzqzL9+6EG
SvK4nBvvh+0/UWIZELyOXKnJ1fnb3P7YwBizlHtCQLJ1c3yoyalTXWTVrEIp98wq
GS+5KRvPDCbGYZMNf/Cr5C5DVZ4F8wVJbkO8yabL7vB+1J0mkmoFuI+l1fM7dqbs
jx9HlWM3mfIj+SYFpQUgQCEdJ1IrAmFqCUcjTJ1wtLCL2yLkOVeoFIZy9llZUGhX
wXGsJ0yxsYXo9BHWlJl2FllrOAVp5a15bSktQ0Ux1YNo4d5uHU3fij7D/Rhc8pU9
ouy3TjXwVILYNkVSRFu6jg/izTXWDFlH41uGBEyayJhqifSX2vj4vnMZ2NbdXsKh
1BLoWAfdyJZBtD8AEQEAAbQdTmV4dXMgVGVzdCA8bm9uZUBleGFtcGxlLmNvbT6J
AdQEEwEKAD4WIQSkdxdiaK0S1hfXBdvNDf+ua4NOGAUCXZibcAIbAwUJA8JnAAUL
CQgHAgYVCgkICwIEFgIDAQIeAQIXgAAKCRDNDf+ua4NOGBh+C/oCiY5VkzXZYZe5
724A4cg526QvZGbc9lt7BGIvFZoZERZJncVjSHN53VJUKOI5iq0V7eNmyBNfhSpG
3TcLXx9ETzmEj3KW87hx1r1Mp6so8p/ZYhYwM0WxYYW7pN9Q+iF708LnIoKtEqee
mibwebVYm+x9bZK7PS2/eBh00DYOBac4PNHEqjjob34mJwp4cMPmpxfhF8CPyBvs
qbZVQ5CQxDT5Sol1jO5VUgzxE7qWSbocdBBMwtRDer67/K9wHopLDwPEOfXJxMmJ
hRzOurhGLS42U5i5POSOe0XehN5J+cLe3UhGVb6dvBI/uRcDG4iFm5Eupq/ECLDs
7MWeQyjtc3eiSG5YBr29BfzILbqLMkSD3FKEraxctVAlX9RiQKeBpfcNE/crS0/T
hVw2iesDfvuHf5MJ5MGF7Ve4lyqvJ2xc239rCM1jU6PzniLvmpjTZdG0lLZxWI58
OS7ZcCGyDg/L1BUOd55XL07ONeEMEFSFWDxVn05P+XKFdA/kaLC5AY0EXZibcAEM
ANh1Wq74MbgwX7YsTWxb0xVFaiOw6YGsIURDaGFq3pqDLlotj+BUHBEeE8WpRTAd
X61qGkEv16a/9RtB6opLOJPy/Q6BWUQxwhrZTzEw547A8yu7pSyAvizypphVugXJ
4Ucb3aZ4yiAzkcI0Ibul+jnPpwvv6KJ2q1a4npTITM+pQCaVOkxkvWnhZcQ5FdF/
GSDgR4jsCbRAAFzQfR2JRoTIRjE8jJMPMaDxPfzfvTzO78mppElT3BZxOmX3kAGz
ygbtyg7NdeiGVGUHamQ5x7NSNw/g9FdzAP81kVh5wVrjZtIVG5y76tjkQSBfPYgS
t97cXgtymZo5tFwrmklS2Im5+bRt+VcFi+a2qzHIyx3R9ie44bJ9jwM3Ar6fPTro
UnQTce7NAM98kn7bQ1S/1cROLjPXSBmCFZqmpZIxrQlb0KADGTBlKlVBENtGLO4a
WQRNlEMPymp31TWoMBL+PhOWjqMLrunjzCYV3Qu5M444RXY1MgXIBKYYjmgvDO3S
WwARAQABiQG8BBgBCgAmFiEEpHcXYmitEtYX1wXbzQ3/rmuDThgFAl2Ym3ACGwwF
CQPCZwAACgkQzQ3/rmuDThh0SQwAmGXXLC52QZ+0zy2qp736iqn4qpHpyMTJLfzx
l+U2ZXgScqwmrWZ7VnfKXV7M+37vWcYh4AVd6o0Oixx93O40JmkzNT4kWa9JxO7t
92ak/1PDKdhJB1U7K7AhGH6h57IckBtB0Kw+tfuJ3XKB76TRUcucsdyvgCBoRayI
q0N/90BXWNil9/k88of/Ap/jF0VN2AVKvIpnn9lCDPMI9MYFN2HqQrw6cI8gNHMp
8D9PydC6QBPRrWFFcq8b3n3PS7MJD609z0eAYzfttS9ZwOKZ2uy/GX5NtYQjuC1Y
7p6Ky/HsE6Qf2YhYJM1uII3y5bdKJ5ZVVyoB7Q+fJ+utth3+KgQZ7i4rEbYagsTa
krFqWttq2OtLbsZaUaYkqVLNp8iVYRS1CO1DU9btcAxHBPsWmearKCRnzhFO60o5
y2SwPdbRAefDPFZ+FSI8ifptlNYyhiS6dwsTdciHf/SZyZvnp+wdZ9JeQMWotAEH
wfP1H4kG2SRX0Zj07jIqPOvnddF+
=0w7O
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by zeitounator** [comment]
Hi. I upgraded the branch to latest master. I'm working on a test case using the cert to check everything is functioning as expected.

**Comment by zeitounator** [comment]
Hi @vitkhab This will finally be merged from #212 which is a rebase of your current work with tests added. The public key is in the test and used to deploy a sample package on debian based distribs.

Thanks again. Cheers !

**Comment by zeitounator** [comment]
As announced, merged with #212.

**Pull request closed without merging**
