### PR TITLE
Allow to use this role with lxd connection plugin

### PR DESCRIPTION
**Pull request by balux**
Some connection plugins like lxd are not supported by the synchronize module. On the other hand uploading a lot of files with the copy module is really slow. 

This PR replaced the synchronize modul with archive/unarchive to upload the script files fast and in a way it is supported for more connection plugins.

### CODE REVIEW

**Comment by zeitounator** [comment]
Will review this soon and think about it. Best approach would be to have ansible synchronize module handle lxd connection type but that might not be so easy...

**Comment by balux** [comment]
The synchronize module is designed to work with rsync, so maybe it will never support a fallback for non ssh based connection plugins. The developers have discussed about it for a while, but that ended up with a few workarounds using copy.

I have used the archive/unarchive pattern for a few of my roles to replace synchronize. It's a lot faster than copy and works with every connection plugin. 

That doesn't mean that I avoid the synchronize module at all. In some use cases, where I know how things are connected, I use it too: Like backups or synchronizing stuff between target hosts. 

I think it's a good practice to avoid it in roles and especially for synchronizing files from role to target.

**Comment by zeitounator** [comment]
Thanks for the feedback.

From memory: docker connection type support for synchronize was introduced in ansible 2.5. So I was just wondering if lxd could be supported as well in a near future. If I take your word, it looks like it is not going to be or at best as some sort unsatisfactory workaround.

Moreover I generally agree on your best practice scenario regarding rsync/unarchive usage.

Checking and merging. Thanks a lot for your contribution.

**Comment by zeitounator** [comment]
Hi @balux,

Just to let you know that, although I merge your changes, I'm going to publish a small "fix" to write the tar.gz file in /tmp rather than in {{ role_dir }}. See #119

**Pull request merged**
