### PR TITLE
Add support for installing the community plugin for apt repositories.

### PR DESCRIPTION
**Pull request by touchardv**
Hello,

Would it be useful to integrate support for installing this feature (apt plug-in)?

Regards,

Vincent

### CODE REVIEW

**Comment by touchardv** [comment]
Closed due to the rebase of the MR... Please re-open if it makes sense to include it @thoteam.

**Comment by zeitounator** [comment]
Hi @touchardv. Sorry for the rebase without any further announcement. The goal was to fix the never passing travis tests to make sure we could have a significant result on the PR.

Regarding your implementation, I've been asked once here to include apt as a plugin and I am literally harrassed internaly at my current work to include several other third party plugins (apt, composer, cpan...) 

My previous point of view was not to include any third party plugins intallation in the role and rely on sonatype including them officially in their base product. Meanwhile, the experience shows this is a long process and that some plugins are mature enough to be used on production.

I'm a now considering adding third party plugins installation as a feature and your contribution is a very good starting point. But I see several things I'd like to enhance:
1. this solution installs apt plugin only. I was wondering if we can provide a global solution for any other third party plugin.
1. the install of the plugin forces an other restart of nexus during the intall process. I'd like to overcome this and make sure nexus is only started once during the process.
1. more generally, I think this role now takes in charge a lot of features (install, general nexus config, reverse proxy config, provisionning) and becomes a little too complicated. I'm thinking of splitting it into several roles. In this scenario, plugin install could be a helper role. If having a global plugin solution is not an option, we could have a simple helper role for each plugin we decide to support.

This was just to share my current thoughts although I have at this exact time no visibility on when I would be able to seriously work on those topics... I'm still interested in your point of view.

Cheers.

**Comment by keitalbame** [comment]
I'm also interested in this apt plugin. We implemented this in a very similar way(using xml instead of blockinfile).

Regarding @zeitounator point 3, it would be very interesting in splitting it. We are using this role to provide the initial setup and importing its tasks to other playbooks like install nginx, configure plugins(Crowd and APT for now) and using variable files to provide a separation of configurations and being able to reconfigure Nexus, without triggering nexus (and nginx) full install.
We only have this work on internal repos but I believe in some point we will push this as some role.

**Comment by touchardv** [comment]
Hi @zeitounator 

At first sight I doubt a simple "global solution for any other third party plugin" is possible. But well, I only tried to get the APT plug-in working. In the near future it could be that I need to also include the CPAN plug-in, then I guess one could check if there are some similarities.
About the restart, that's right, this could be improved.

**Pull request closed without merging**
