### PR TITLE
Fix repo creation for Nexus 3.21+ (#246)

### LINKED ISSUE #246: Role broken with nexus 3.21
Some api changes are causing groovy scripts to fail. First identified: `create_repos_from_list`. Have to check if there are any others.

See for example: https://travis-ci.org/ansible-ThoTeam/nexus3-oss/jobs/652746284

Will work on that ASAP. In the mean time please stay with version 3.20.

Any help/PR appreciated.

### PR DESCRIPTION
**Pull request by noroutine**
With backward compatibility

Fixes #246

### CODE REVIEW

**Comment by noroutine** [comment]
I have both 3.20 and 3.21 instances, tested the fix on both

**Comment by noroutine** [comment]
```
Testing groovy syntax for ./files/groovy/create_repos_from_list.groovy
PASSED
```

**Comment by zeitounator** [comment]
Looks like the rest of the fails is only related to molecule 3.0 which is already fixed in #247. Your fix for createRepo looks much better than the one I was working on. I'm going to mix all and take the best out of everything for a coherent release. Thanks.

**Comment by zeitounator** [comment]
Just to let you know I've taken your commit in #247 so I'm closing this now. There were some other changes needed for idempotence. I'm finalising some other fixes and this will be released soon.

**Pull request closed without merging**
