### PR TITLE
Feat/script api

### PR DESCRIPTION
**Pull request by Serienmorder**
Implement RESTFUL scripting API changes.

### CODE REVIEW

**Comment by Serienmorder** [comment]
@zeitounator I can't figure out what that set -e is, and why it continues to fail.

**Comment by zeitounator** [comment]
[`set` is a bash built in](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html). `set -e` is setting bash to exit immediately on first non zero return code.

But this is not actually the failing command. The entire piece of script that is failing is
```
set -e
yamllint .
ansible-lint
flake8
```
And in this case, it is the last `flake8` which returns a non-zero status. You can run those tests locally with `molecule lint`. It fails because your python code does not pass all the PEP coding standards tests.

Besides that, and even though I'm quite impressed by the amount of work you've done (on this PR and others) and its overall quality, I'm a little confused.

In the current role, registering the scripts in nexus is already done, working, tested, idempotent, optimized (only update non existing scripts with a little trick and a possible bypass to force)... and using the Nexus API correctly for all that.

Using the `uri` module is easy to understand and to debug for everyone (even sysadmins that don't code in python). It is more than sufficient to interact simply with the API. Why would we (I..) want to create and maintain a custom module for that (which more or less looks like a super wrapper around `uri` when we look at its usage) ?

I effectively want to drop some of the problematic groovy scripts, but not to create an other custom maintenance burden unless it is absolutely necessary. And I am really not on a path where I want to create a custom module for each object to interact with.

I am not closed to adding custom developments when they prove to be necessary. I do have a custom filter in the role which was precisely made to overcome problems parsing returns from groovy scripts which were getting a nightmare. If you want to understand why, [here is my questioning before I decided to walk that path](https://stackoverflow.com/questions/55384113/elegant-way-to-handle-from-json-filter-failure-with-default-value).

Moreover, some of the groovy scripts will probably remain because I do not think we can have an equivalent in terms of performance and idempotence. I maintain a 500+ users 300+ repos instance. If we only take repositories, it is much more convenient and fast to send a full list to nexus, let groovy to the job and return a result list managing overall idempotence as today, rather than calling the API once to get the full list of repos, call a different endpoint for each format/type to create unexisting repos, call a different endpoint for each format/type to update existing repos, and forget about idempotence to report 'ok' all the time because there is no way to know if something changed or not.

This current review does not mean I'll reject upfront all your custom module propositions and I need some time to look at the others. (I'm totally overbooked and delaying working on this until I'm forced to for production reasons....). But I will carefully weigh up the risk, maintainability, added value... before accepting. And as you understand, this one is not passing through this screening. I'll keep you updated on the others when I can.

Cheers.

**Comment by Serienmorder** [comment]
Yup no problem that was just the feedback I was looking for.
I understand you're busy. So I'll move onto another project until you're able to review the others.
The set -e makes sense. i'm surprised no one in the molecule IRC or the ansible IRC caught that..
After going down the road of custom modules, I kind of figured that adding additional code wasn't going to be what you wanted.

**Comment by zeitounator** [comment]
As explained, I'm not closed to this as long as there is a read added value compared to what the role is doing today. And please continue to contribute ! I'll review your other PRs shortly as I have to prepare a new release to integrate changes I personally need rather urgently (#257). See you soon !

**Pull request closed without merging**
