### PR TITLE
Fix for Python 3.x SELinux packages on RHEL/CentOS 8

### PR DESCRIPTION
**Pull request by EBCEEB**

### CODE REVIEW

**Comment by zeitounator** [comment]
close/open to re-trigger build which got struck on travis side

**Comment by zeitounator** [comment]
Hi @EBCEEB. I am on the line with travis-ci support to understand why your PR does not want to go through CI. Can you please try to connect to https://travis-ci.org with your github account and let me know when it's done ? Thanks in advance.

**Comment by EBCEEB** [comment]
I thought is is due to `@` in branch name, and I recreated PR: https://github.com/ansible-ThoTeam/nexus3-oss/pull/235

... but looks like there is some other reason

I logged in to Travis, and there was an acknowledgement that my account "is subject for abuse". Don't know what it means.

**Comment by zeitounator** [comment]
Thanks for your reply. I'm passing the information back to travis support. I'll keep you updated

**Comment by EBCEEB** [comment]
> For whatever reason your account was flagged. Travis support just unflagged it after my follow-up ...

Good! Thank you!

**Pull request merged**
