### PR TITLE
Add support for go repos

### PR DESCRIPTION
**Pull request by enicholson125**
This enables the creation of golang repos

### CODE REVIEW

**Comment by jose-nferx** [comment]
I have a question because as I know, nexus3 does not support go hosted repositories. Only proxy and group. If authorization is required Athens must be used and it will proxy it. 

That is the configuration we have and I patched your outstanding role to have go and R records. I was happy to see your update but I am wondering if you have additional information that go hosted repositories are supported now since you allowed it on the role. 

https://help.sonatype.com/repomanager3/formats/go-repositories

Thanks.

**Comment by enicholson125** [comment]
> I have a question because as I know, nexus3 does not support go hosted repositories. Only proxy and group. If authorization is required Athens must be used and it will proxy it.
> 
> That is the configuration we have and I patched your outstanding role to have go and R records. I was happy to see your update but I am wondering if you have additional information that go hosted repositories are supported now since you allowed it on the role.
> 
> https://help.sonatype.com/repomanager3/formats/go-repositories
> 
> Thanks.

Thanks, that's a good point. I don't have any additional that go hosted repositories are possible, I only need go proxies for my use case so didn't fully think through putting hosted repos on there. I'll correct the PR to not include hosted go repositories. 

I didn't understand what you meant by patching my outstanding role to have go and R records?

**Comment by jose-nferx** [comment]
That is a pity!. I thought it was already supported. 

I had a pre task on my playbook to add to your role the same lines that you have added in the commit for R and go since. Therefore I could clone it and pull and not doing changes. That is what I meant by patching the role....  It was just in case your code would changed that I would always have the lines added automatically. I am lazy! 

Thanks for your response. By the way could you add R. Lol!!!! It works like a charm just by adding the 3 types of repos like you did for go initially. .... therefore R would be supported and I do not have to run my pre task......

Thanks 

Sent from my iPhone

> On 23 Jun 2020, at 10:27, Eleanor Nicholson <notifications@github.com> wrote:
> 
> ﻿
> I have a question because as I know, nexus3 does not support go hosted repositories. Only proxy and group. If authorization is required Athens must be used and it will proxy it.
> 
> That is the configuration we have and I patched your outstanding role to have go and R records. I was happy to see your update but I am wondering if you have additional information that go hosted repositories are supported now since you allowed it on the role.
> 
> https://help.sonatype.com/repomanager3/formats/go-repositories
> 
> Thanks.
> 
> Thanks, that's a good point. I don't have any additional that go hosted repositories are possible, I only need go proxies for my use case so didn't fully think through putting hosted repos on there. I'll correct the PR to not include hosted go repositories.
> 
> I didn't understand what you meant by patching my outstanding role to have go and R records?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 
CONFIDENTIALITY NOTICE: This E-Mail is intended only for the individual or 
entity to which it is addressed and may contain information that is 
confidential. If you have received this communication in error, do not 
distribute. Please delete the original message and immediately notify the 
sender.

**Comment by enicholson125** [comment]
Haha, no worries. It looks like there's an older PR out already to add R (https://github.com/ansible-ThoTeam/nexus3-oss/pull/274) so I'll leave the R adding to that one

**Comment by jose-nferx** [comment]
Thanks. It is only 2 minutes. Lol!!!


Sent from my iPhone

> On 23 Jun 2020, at 17:34, Eleanor Nicholson <notifications@github.com> wrote:
> 
> ﻿
> Haha, no worries. It looks like there's an older PR out already to add R (#274) so I'll leave the R adding to that one
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 
CONFIDENTIALITY NOTICE: This E-Mail is intended only for the individual or 
entity to which it is addressed and may contain information that is 
confidential. If you have received this communication in error, do not 
distribute. Please delete the original message and immediately notify the 
sender.

**Pull request merged**
