### PR TITLE
Email API integration

### PR DESCRIPTION
**Pull request by Serienmorder**
Supports the email API of nexus that is in 3.22.

### CODE REVIEW

**Comment by Serienmorder** [comment]
None of those should have failed?

**Comment by Serienmorder** [comment]
@zeitounator I think a new var needs be put into use for the API interaction? Or is there something already there that I'm missing? Needs to have the IP and a port number if applicable..

**Comment by Serienmorder** [comment]
I'm thinking of doing it in this style as a "first wave" and then wrapping them all around with action plugins. What do you think of that. Get moving forward on API integration. Get more generic as things continue.

**Comment by zeitounator** [comment]
Hi. I need to review this and take some decisions. I will have time for that next week probably. At first glance, I'm not really sure about the specific module, and I'm not really comfortable with tests vars and files being added to the role itself when they should be in molecule only. But I really need to read that other than quickly and tired at 11pm my time after a particularly hard week of work... Thanks, keep you updated.

**Comment by Serienmorder** [comment]
Yup I get that. I'm willing to change whatever you need. The nice thing about the tests is that it can show other ways the module can be used? One of the reasons I opened the PR was for you to see what I've been working on and to confirm I should still continue going that way forward.

**Comment by Serienmorder** [comment]
Fixed the issues. Except whatever set -e does. I can't seem to find anything about it with ansible-lint, or molecule. So I'm at a loss why that is failing.

**Pull request closed without merging**
