### PR TITLE
Adding Support for Use With sonatype/nexus3 Docker Images

### PR DESCRIPTION
**Pull request by psharkey**
This is to address an enhancement requested in https://github.com/ansible-ThoTeam/nexus3-oss/issues/86.

The `default-docker` molecule scenario added here may be used for testing:

`molecule test -s default-docker`

Normally this would be used with a `docker` connection to a [sonatype/nexus3](https://hub.docker.com/r/sonatype/nexus3) container as the `root` user:
`ansible-playbook -i '<YOUR_CONTAINER_NAME>,' -c docker -u root <YOUR_PLAYBOOK>.yml`

### CODE REVIEW

**Comment by zeitounator** [comment]
Thanks for this ongoing work @psharkey. Being able to use the 'provisionning' part of the role separately from the install has been on my mind for quite a while. Being able to use the role for plain docker containers as well.

Your general idea looks good and we probably can explore further if this can lead to a fully usable/mainteanable result.

In your current implementation, ther is one major problem: the `install-docker.yml` file you created is duplicating most of the logic in `install.yml`. This would require to do the work twice if we need to change something (add a new check related to nexus version for example) and this is really error prone. Do you already have an idea on how to address this issue ?

My major concern about such feature implementation is the amount of refactoring needed to implement them in a sustainable and transparent way.

**Comment by psharkey** [comment]
@zeitounator I'm going to try and eliminate the duplication. Now that there's a molecule scenario in place for docker as well it will be easier to iterate on this problem.  I'll try to keep the changes in each commit small and can squash these later if needed.

**Comment by psharkey** [comment]
@zeitounator This should be ready for review now when you get a chance.

**Comment by zeitounator** [comment]
Hi @psharkey. Thanks a lot for all this. I really appreciate.

I'm am currently very busy finishing a contract. Then I'm am moving moving for a 3 month expatriation with all my family. I should be able to have a look at this in about 8-10 days once we are settled in our temporary home. Thanks in advance for your patience.

**Comment by psharkey** [comment]
@zeitounator No worries. In the meantime if anyone wants to use this and #173 they can use [ansible-galaxy install -r requirements.yml](https://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html#installing-multiple-roles-from-a-file) with a `requirements.yml` file like:

```yaml
---
# Install a role from a specific git branch
- name: nexus3-oss
  src: https://github.com/psharkey/nexus3-oss
  version: origin/develop
```

**Comment by zeitounator** [comment]
I did not abandoned the idea. But there have been a lot of changes requiring to rework this PR. I also have some other ideas to add like a version detection of the image. Just need to find time to work on it.

**Comment by zeitounator** [comment]
This was a good idea at start but this branch as diverged too much ans I missed time to work on the subject.

One next role's big change is probably to move fully to the api (starting with ldap which is the most critical and fragile groovy implementation). Once this is done, It will be a lot easier to separate installation from provisioning and I will probably restart working on this. But I have to close that one as is. Thanks for your time and sorry it did not make it to a conclusion.

**Pull request closed without merging**
