### PR TITLE
Add support for removing users

### PR DESCRIPTION
**Pull request by wiget**

### CODE REVIEW

**Comment by wiget** [comment]
Hi @zeitounator What do you think about this PR?

**Comment by zeitounator** [comment]
Hi @wiget and thanks for your interest.

* As is, this PR will simply do nothing in this role as the file `delete_user_each.yml` is not included anywhere from tasks/main.yml or any subsequent inclusions. Can you provide a scenario where you would find this usefull and how it could be integrated in the role (with subsequent vars and tasks) ?
* I didn't get any time to test that the groovy script is functional and will not fire errors in some cases (e.g. deleting a user that is not currently declared on nexus).

My view of this role is that it installs and provision nexus over and over with the same repository/users/blobstores/tasks. I only see an interest on deleting local user if you decide to remove one from your vars and you want to make sure it is definitely removed from your nexus service. In this case it might be better to
* add a "state" variable in each users in the list which would default to "present"
* modify the `setup_user.groovy` so it would (try to) delete the user if state is "absent" and continue to do it's job AS-IS if state is "present"

**Comment by wiget** [comment]
Hi @zeitounator 

Thanks for reviewing. I updated this PR to follow your's suggestions.

**Comment by zeitounator** [comment]
Hi @wiget and thanks for working on this.

This looks better and could be used in the role. Meanwhile, it still needs:
- Testing (included in molecule so it is integrated in travisCI)
- Documentation and default variables updates to explain how to use it

The role is actually in a stable state so I don't have a clear date for the next version since I don't have any bug or incomplete feature to fix. I will integrate your suggestion with the next release if tests are successful.

**Comment by wiget** [comment]
Documentation updated. Also I added 2 entries to `nexus_local_users`, so testing in molecule should cover creating and removing users (at least removing non-existing user).

**Comment by zeitounator** [comment]
Hi @wiget. I'm really sorry for the delay. Thanks a lot for your contribution, this is going to next release.

**Pull request merged**
