### PR TITLE
change layoutPolicy to deployPolicy for Yum repository closes #380

### LINKED ISSUE #380: Unable to set Layout Policy for yum repositories
Setting the attribute layout_policy for yum repo seems to have no effect.

Looking at the file [create_repos_from_list.groovy](https://github.com/ansible-ThoTeam/nexus3-oss/blob/main/files/groovy/create_repos_from_list.groovy), the layout_policy ends up populating the layoutPolicy field int the repo config.

Looking at nexus code, it should populate deployPolicy field rather than layoutPolicy field.

### PR DESCRIPTION
**Pull request by brianveltman**
Update create_repos_from_list.groovy

### CODE REVIEW

**Comment by brianveltman** [comment]
fixes #380

**Review by zeitounator — CHANGES_REQUESTED** [review]
This is apparently not meeting the target. See the errors in CI. Extract:
```json
        {
            "error_msg": "javax.validation.ConstraintViolationException: attributes[maven].layoutPolicy: must not be null",
            "format": "maven2",
            "name": "central",
            "status": "error",
            "type": "proxy"
        },
        {
            "error_msg": "javax.validation.ConstraintViolationException: attributes[maven].layoutPolicy: must not be null",
            "format": "maven2",
            "name": "jboss",
            "status": "error",
            "type": "proxy"
        },
        {
            "error_msg": "javax.validation.ConstraintViolationException: attributes[maven].layoutPolicy: must not be null",
            "format": "maven2",
            "name": "private-release",
            "status": "error",
            "type": "hosted"
        },
```

**Comment by brianveltman** [comment]
I will fix this and push the changes later today :-)

**Comment by brianveltman** [comment]
Ah I see, inconsistency on the Nexus part. For yum its called deployPolicy. For maven its called layoutPolicy.

**Review by zeitounator — APPROVED** [review]
It's good enough with a single var on nexus side since the UI uses the same name. We can always change that later if need be. Thanks for the fix.

**Pull request merged**
