### PR TITLE
fixed ldap groovy

### LINKED ISSUE #224: ldap setup error
Nexus Version 3.20.x changed groovy api for ldap configuration.
We get the following error:

FAILED! => {"changed": false, "connection": "close", "content": "{\n  \"name\" : \"setup_ldap\",\n  \"result\" : \"org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:\\nScript15.groovy: 13: You cannot create an instance from the abstract interface 'org.sonatype.nexus.ldap.persist.entity.LdapConfiguration'.\\n @ line 13, column 18.\\n   def ldapConfig = new LdapConfiguration()\\n

### PR DESCRIPTION
**Pull request by fhsctv**
Using LdapConfigurationManager to get ldapConfig

Fixes #224

### CODE REVIEW

**Comment by zeitounator** [comment]
While testing to merge, I still get an error when setting the name of the ldap connection.
```
javax.script.ScriptException: groovy.lang.MissingMethodException: No signature of method: java.util.LinkedHashMap.setName() is applicable for argument types: (java.lang.String) values: [Mock ldap server]\nPossible solutions: getAt(java.lang.String), take(int)
```

I'm trying to find a solution. But if you come by @fhsctv and you managed to fix that with a config change or whatever, let me know so that I don't reinvent the wheel. Thanks.

**Comment by zeitounator** [comment]
Thanks for all this ! The ldap api is actually internal and not really documented. So this kind of collateral dammage had to be expected one day. Will review and fix this ASAP.

**Comment by Gm3z** [comment]
> This does only work when the ldap connection already exists.
> I have added
> `
> ...
> }
> if (!update) {
> ldapConfig = ldapConfigMgr.newConfiguration()
> }
> 
> ldapConfig.setName(parsed_args.name)
> `
> 
> Due to this rerason.
> Maybe there are better solutions like always creating a new Configurations, but i don't know and i could not find the sources for the nexus ldap Plugin to understand more.

This solution works for me when I create a new LDAP Connection, but when I try to update the connection don't work, the log show these errors:

`javax.script.ScriptException: groovy.lang.MissingMethodException: No signature of method: java.util.LinkedHashMap.setName() is applicable for argument types: (java.lang.String) values: [Mock ldap server]\nPossible solutions: getAt(java.lang.String), take(int)`

If I write this line: ldapConfig.setName(parsed_args.name) into the If the next error that the log show me is:
`javax.script.ScriptException: groovy.lang.MissingMethodException: No signature of method: java.util.LinkedHashMap.setName() is applicable for argument types: (java.lang.String) values: [Mock ldap server]\nPossible solutions: getAt(java.lang.String), take(int)`

I hope that this error will have a solution ASAP.
Thank you!

**Comment by zeitounator** [comment]
Working solution on the launchpad. Sorry for this tremendous delay.

**Pull request merged**
