### PR TITLE
fix nexus_tmp_dir

### PR DESCRIPTION
**Pull request by ibalago**
replace /tmp by {{ nexus_tmp_dir }}

### CODE REVIEW

**Comment by ibalago** [comment]
I love your role, and I use it since alot!
I create a ansible docker image with a non-root user.
When I use your role, automatically the task to archive script use /tmp.
This pull request allow everyone to manage where to put tmp files.

**Review by zeitounator — COMMENTED** [review]
These two tasks are related to localhost (create a temporary archive of all groovy scripts on the controller and upload it to the target).

I can perfectly understand (although I don't see a real use case) that you might want to create that very volatile file on the controller in an other location. Meanwhile, `nexus_tmp_dir` is definitely not the correct location: this is the nexus temporary dir on the target and in most usual cases, it will not exist on the controller as this is highlighted by the ci on travis failing for all scenario on the archive task.

My opinion is that we do not need to change this at all and to add more complexity in this role. Meanwhile, **if you can convince me this is an absolute need**, I **could** accept a PR but in this case you would need to:
1. declare a new variable in defaults (e.g. `nexus_local_tmp_dir`)
1. add a task to make sure that directory exists on the controller
1. use that dir to create the archive and upload it

Once again, I think it's just a little too much to create a highly volatile tar file in a directory which exists and is world writeable in all our target compatible OS.

**Comment by ibalago** [comment]
Hello,
this is the log when I use your role in an Ansible docker image...
`TASK [ansible-thoteam.nexus3-oss : Create directories to hold current groovy scripts for reference] ***
ok: [nexus] => (item=/data/nexus/groovy-raw-scripts/current)
ok: [nexus] => (item=/data/nexus/groovy-raw-scripts/new)
TASK [ansible-thoteam.nexus3-oss : Archive scripts] ****************************
changed: [nexus]
TASK [ansible-thoteam.nexus3-oss : Upload new scripts] *************************
fatal: [nexus]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/nexus-upload-groovy-scripts.tar.gz' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
PLAY RECAP *********************************************************************
nexus                      : ok=50   changed=4    unreachable=0    failed=1    skipped=31   rescued=0    ignored=0  `
Maybe the only thing is to use "remote_src" option?

**Comment by zeitounator** [comment]
@ibalago : can you please double check if the file is present in your tmp folder on the controller after the task `Archive scripts` ? There is really something I don't get. And no the solution is not to use `remote_src`. The workflow is 

Create a tar.gz of groovy script in controller tmp => upload to target => unarchive on target in reference directory

So the file is definitely not on the target for the copy task.

**Comment by ibalago** [comment]
@zeitounator : thank you very much for your answer!

I put a check file exist control between "Archive scripts" and "Unarchive scripts" task like you propose.

All work perfectly now.

**Comment by zeitounator** [comment]
Considering case closed.

**Pull request closed without merging**
